version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-code-assistant-api
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend/:/app
      - ./logs:/app/logs
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - ai-assistant-network

  # Frontend Service (Development mode with hot reload)
  frontend:
    image: node:18-alpine
    container_name: ai-code-assistant-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped
    networks:
      - ai-assistant-network

networks:
  ai-assistant-network:
    driver: bridge
